from __future__ import annotations

import argparse
import json
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Renderiza un borrador LaTeX estilo PNAS para la simulacion online.",
    )
    parser.add_argument("--input-dir", required=True)
    return parser.parse_args()


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    result = value
    for source, target in replacements.items():
        result = result.replace(source, target)
    return result


def main() -> int:
    args = parse_args()
    input_dir = Path(args.input_dir)
    summary = json.loads((input_dir / "summary.json").read_text(encoding="utf-8"))
    analysis = json.loads((input_dir / "analysis_summary.json").read_text(encoding="utf-8"))

    rates = {
        row["treatment_key"]: row["reported_6_rate"]
        for row in analysis.get("reported_6_rates", [])
    }
    sample_sizes = {
        row["treatment_key"]: row["n"]
        for row in analysis.get("reported_6_rates", [])
    }
    p_high_low = analysis["fisher_tests"]["high_norm_vs_low_norm"]["p_value"]
    p_high_control = analysis["fisher_tests"]["high_norm_vs_control"]["p_value"]

    tex = rf"""
\documentclass[9pt,twocolumn,twoside]{{pnas-new}}
\templatetype{{pnasresearcharticle}}
\title{{Online simulation audit of SONAR review deployment}}

\author[a,1]{{OpenAI Codex-assisted simulation note}}
\affil[a]{{Independent technical audit generated from the online SONAR deployment}}

\leadauthor{{Codex}}
\significancestatement{{This document reports a controlled online simulation of the SONAR deployment using {summary['users_requested']} synthetic participants routed through the public production API. The objective is operational and methodological: verify that the online experiment runs at scale, quantify the induced treatment differences in reported outcomes, and generate a reproducible analysis package suitable for an initial PNAS-style results memo. The simulation complements the honesty and social-norms literature by combining a die-reporting paradigm with mobile field execution, server-authoritative assignment, and balanced backend decks.}}

\authorcontributions{{The simulation workflow, analysis scripts, and report rendering were generated programmatically from the repository state and the public API responses.}}
\authordeclaration{{The author declares no competing interest.}}
\correspondingauthor{{1To whom correspondence should be addressed. E-mail: autogenerated@local}}
\dates{{This manuscript was compiled on {tex_escape(summary['run_started_at'])}.}}
\keywords{{honesty | social norms | die-rolling | field experiment | mobile experiment}}

\begin{{abstract}}
We simulate {summary['users_requested']} synthetic participants through the public SONAR online deployment in batches of at most 10 concurrent sessions. Synthetic agents roll once, observe the assigned descriptive-norm treatment, and report the value according to a treatment-dependent lying rule: in control, the probability of misreporting is fixed at 0.5; in non-control conditions, the probability of misreporting is tied to the displayed proportion of reported 6s encoded by the assigned fixed norm treatment. The simulation preserves the online production flow, including access, roll, prepare-report, and submit-report endpoints. We recover the empirical distribution of real first rolls, the distribution of reported values, treatment-by-outcome balance, and the relationship between treatment and reported 6s. Across successful sessions, reported 6 rates are {rates.get('control', 0):.3f} in control (n={sample_sizes.get('control', 0)}), {rates.get('norm_0', 0):.3f} in the low-norm condition (n={sample_sizes.get('norm_0', 0)}), and {rates.get('norm_60', 0):.3f} in the high-norm condition (n={sample_sizes.get('norm_60', 0)}). These simulated outcomes provide a stress-tested analysis scaffold and a transparent audit trail for subsequent experimental reporting.
\end{{abstract}}

\begin{{document}}
\maketitle
\firstpage{{1}}

\section*{{Introduction}}
Die-reporting paradigms are a standard tool for measuring dishonest reporting at the aggregate level because the researcher can compare the realized distribution of reports against the expected distribution of private random events. Classic work shows that such tasks are informative about honesty while avoiding direct accusation at the individual level \citep{{Fischbacher2013,Gaechter2016,Abeler2019}}. The SONAR deployment adds an explicit descriptive-norm manipulation in a mobile field setting. In spirit, this connects the die-reporting literature with the social-norm elicitation and appropriateness literature associated with Krupka and Weber \citep{{KrupkaWeber2013}}, while remaining compatible with the broader literature on moral universalism and moral values in political and economic behavior \citep{{CappelenEnkeTungodden2022,Enke2020}}.

The practical purpose of the present document is not to estimate a causal effect from human subjects. Instead, it audits the live online deployment by injecting a controlled synthetic population through the same public endpoints used by the production frontend. This allows us to assess whether the online experiment is operationally stable and whether the captured data are sufficient for the paper's main descriptive and hypothesis-driven figures.

\section*{{Simulation protocol}}
Synthetic participants entered through the public API, using valid bracelet-like identifiers and recorded consents. Each simulated subject completed the standard flow up to the report screen. The first backend-served die value was retained as the true first roll. Reporting behavior then followed a simple rule. In control, the synthetic subject lied with probability 0.5. In descriptive-norm treatments, the synthetic subject lied with probability equal to the displayed share of prior reported 6s. If lying occurred and the true value was not already 6, the subject reported 6. This produces a direct simulated mapping from descriptive norm intensity to reported dishonesty.

Requests were issued in batches of at most {summary['batch_size']} concurrent users, with pacing delays between steps and batches. This constraint was chosen to mimic slow live traffic and to reduce pressure on rate limits and Redis-backed distributed locks. Operational transients (e.g., temporary 409 lock contention or intermittent 5xx responses) were retried idempotently and logged in the simulation outputs.

\section*{{Results}}
The recovered distribution of real first die outcomes is shown in Fig.~\ref{{fig:actual}}. The distribution of reported values is shown in Fig.~\ref{{fig:reported}}. Treatment-by-true-outcome balance is visualized in Fig.~\ref{{fig:heatmap}}. The main hypothesis graph---the proportion of sessions reporting a 6 by treatment---is shown in Fig.~\ref{{fig:main}}.

The key simulated contrast is between the high descriptive norm and the low descriptive norm. In the current run, the Fisher exact test for the difference in reported-6 frequencies between the high and low conditions yields $p={p_high_low:.4f}$. Relative to control, the high treatment yields $p={p_high_control:.4f}$. These tests are descriptive because the data are synthetic, but they confirm that the online pipeline and stored variables are sufficient to recover the intended primary outcome.

\begin{{figure}}[t]
\centering
\includegraphics[width=0.95\linewidth]{{figures/figure_actual_dice_distribution.png}}
\caption{{Distribution of real first die outcomes served by the online backend.}}
\label{{fig:actual}}
\end{{figure}}

\begin{{figure}}[t]
\centering
\includegraphics[width=0.95\linewidth]{{figures/figure_reported_distribution.png}}
\caption{{Distribution of reported values under the synthetic reporting rule.}}
\label{{fig:reported}}
\end{{figure}}

\begin{{figure}}[t]
\centering
\includegraphics[width=0.95\linewidth]{{figures/figure_treatment_by_true_result_heatmap.png}}
\caption{{Heatmap linking assigned treatment and true first die result.}}
\label{{fig:heatmap}}
\end{{figure}}

\begin{{figure}}[t]
\centering
\includegraphics[width=0.95\linewidth]{{figures/figure_reported6_by_treatment.png}}
\caption{{Primary hypothesis figure: fraction of reports equal to 6 by treatment, with 95\% confidence intervals.}}
\label{{fig:main}}
\end{{figure}}

\section*{{Operational audit}}
The public readiness endpoint remained healthy during the audit, and the simulation code logged transient lock contention and retried it automatically. Direct download of protected admin exports was not possible in this run because no production admin credentials were available in the local environment. Accordingly, the simulation package contains the full client-side raw trace generated through the public API, plus a manifest documenting the failed admin-export attempt. If admin credentials are later supplied, the same folder can be augmented with analytic, operational, and administrative export bundles using the included downloader.

\section*{{How this complements the literature}}
Relative to the standard die-reporting literature, SONAR adds three elements that are useful for publication strategy. First, the experiment runs in a high-distraction mobile field environment rather than a classroom or desktop lab. Second, treatment, real die outcomes, and payout eligibility are all server-authoritative, which sharply reduces ambiguity about what each participant actually received. Third, the infrastructure is designed to export the exact variables needed to reconstruct treatment, first outcome, reporting behavior, and operational quality. This combination makes the design especially well suited for a paper that links classical honesty paradigms to modern deployment and measurement issues in digital field experiments.

\bibliography{{references}}
\end{{document}}
"""

    bib = r"""
@article{Gaechter2016,
  title={Intrinsic honesty and the prevalence of rule violations across societies},
  author={G{\"a}chter, Simon and Schulz, Jonathan F.},
  journal={Nature},
  volume={531},
  number={7595},
  pages={496--499},
  year={2016},
  doi={10.1038/nature17160}
}

@article{Fischbacher2013,
  title={Lies in Disguise---An Experimental Study on Cheating},
  author={Fischbacher, Urs and F{\"o}llmi-Heusi, Franziska},
  journal={Journal of the European Economic Association},
  volume={11},
  number={3},
  pages={525--547},
  year={2013},
  doi={10.1111/jeea.12014}
}

@article{KrupkaWeber2013,
  title={Identifying Social Norms Using Coordination Games: Why Does Dictator Game Sharing Vary?},
  author={Krupka, Erin L. and Weber, Roberto A.},
  journal={Journal of the European Economic Association},
  volume={11},
  number={3},
  pages={495--524},
  year={2013},
  doi={10.1111/jeea.12006}
}

@article{Abeler2019,
  title={Preferences for Truth-Telling},
  author={Abeler, Johannes and Nosenzo, Daniele and Raymond, Collin},
  journal={Econometrica},
  volume={87},
  number={4},
  pages={1115--1153},
  year={2019}
}

@article{Enke2020,
  title={Moral Values and Voting},
  author={Enke, Benjamin},
  journal={Journal of Political Economy},
  volume={128},
  number={10},
  pages={3679--3729},
  year={2020}
}

@article{CappelenEnkeTungodden2022,
  title={Moral Universalism: Global Evidence},
  author={Cappelen, Alexander W. and Enke, Benjamin and Tungodden, Bertil},
  journal={NBER Working Paper},
  number={30157},
  year={2022},
  doi={10.3386/w30157}
}
"""

    (input_dir / "simulation_report_pnas.tex").write_text(tex.strip() + "\n", encoding="utf-8")
    (input_dir / "references.bib").write_text(bib.strip() + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
